# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 10:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
